### ISSUE TITLE
Money.fromDecimal is subject to floating point calculation errors

### ISSUE THREAD

**Issue by anujbiyani** [macor161/ts-money#1]
[These lines](https://github.com/macor161/ts-money/blob/master/index.ts#L126-L127) are subject to floating point errors:
```javascript
let precisionMultiplier = Math.pow(10, currency.decimal_digits)
let resultAmount = amount * precisionMultiplier
```

For example:
![image](https://user-images.githubusercontent.com/305254/44430944-2ebef280-a551-11e8-8411-0db44163b48e.png)

The result of this calculation is [assumed to be an integer](https://github.com/macor161/ts-money/blob/master/index.ts#L73):
```javascript
if (!isInt(amount))
    throw new TypeError('Amount must be an integer')
```
but because of floating point calculation inaccuracies that's not always the case.

It's easy to workaround this issue by passing a `rounder` to `Math.fromDecimal`, but I feel like this issue is better fixed by ts-money itself, e.g. by using a default rounder.

Would you be open to a PR to address this?

**Comment by macor161** [comment]
Hi @anujbiyani 
Thank you very much for submitting this issue. I will create a patch this week.

**Comment by anujbiyani** [comment]
In case it helps, here's the `rounder` function I'm using:
```
export function roundTo(n: number, digits: number = 0): number {
  let negative = false;

  if (n < 0) {
    negative = true;
    n = n * -1;
  }

  const multiplicator = Math.pow(10, digits);

  n = parseFloat((n * multiplicator).toFixed(11));
  n = +(Math.round(n) / multiplicator).toFixed(digits);

  if (negative) {
    n = +(n * -1).toFixed(digits);
  }

  return n;
}
```

It's a Typescript version of https://stackoverflow.com/questions/15762768/javascript-math-round-to-two-decimal-places/15762794#15762794

**Comment by macor161** [comment]
Terribly sorry for the delay, I've been really busy lately. An update will be plublished by monday.
Also, a new version of the library using native [BigInt](https://github.com/tc39/proposal-bigint) is currently in the making.

**Comment by anujbiyani** [comment]
No worries, thanks for the update! Let me know if I can help.

**Comment by macor161** [comment]
@anujbiyani The issue should be fixed now. Basically, we now always use the rounder function in `fromDecimal`. If no rounder is provided, Math.round is used by default.

Here is the [commit](https://github.com/macor161/ts-money/commit/a2d486794dea6e6807d10740183ff3fd7e18cf4c)

Let me know if you think another approach would be better suited to fix this problem.

Thanks again for signaling the issue, really appreciated! :)

**Comment by anujbiyani** [comment]
Looks great! Thank you.
