### ISSUE TITLE
Why ECMAScript target version is ES6 but not ES5?

### ISSUE THREAD

**Issue by maksim-kosolapov** [macor161/ts-money#2]
IE doesn't support ES6 syntax, so I need to transpile ts-money module to ES5, seems to be better change target version to ES5 here to avoid similar problems.

**Comment by macor161** [comment]
Hi @maksim-kosolapov, thanks for the suggestion. ES6 was chosen mainly because the vast majority of browsers and NodeJs support it. For what browser do you need ES5 exactly, Internet Explorer?

**Comment by maksim-kosolapov** [comment]
Yes, IE11 doesn't support ES6 yet. And as i know most node modules compiled in ES5, so no need to transpile them with babel to speed up build.

**Comment by macor161** [comment]
Closing this now that IE is deprecated.
